# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02d71d37ad3676b6cbc2cd8abb77ee14ae5f132654256f02521a7d898a3fd32adb74bad50c76a6ef0e8e8c069878ff3cc994e3fe2bd4e04dd2d3d5c39c5947d8

test:
  secret_key_base: 45c316d56fdfe203ae173b6cd3ebaa25cd7387cd429dbfca57d34307a0661d0c7f3487e908669ca99246db6277c8d2ebacea68a2fbce6d20ddc49cf0ec111d6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
